// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbrtnhpecnzbdjuwyyaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicnRuaHBlY256YmRqdXd5eWFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzIyNTUsImV4cCI6MjA2NzAwODI1NX0.7x2WpOjq-_LTOO_2Txtx72A3KMg7Knl1oSd3Le_SN3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});